name 'alfiecookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures alfiecookbook'
long_description 'Installs/Configures alfiecookbook'
version '0.1.0'
